apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-microservice
  labels:
    app: users-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-microservice
  template:
    metadata:
      labels:
        app: users-microservice
    spec:
      containers:
        - name: users-microservice
          image: ghcr.io/ricardoMerinoUBB2021/ProyectoGPSUsersMicroservice:latest # <-- update as needed
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3001"
            - name: API_PREFIX
              value: "/api/v1"
            - name: DB_HOST
              value: "<DB_HOST>" # <-- update for your environment
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: users-microservice-secrets
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: users-microservice-secrets
                  key: DB_PASS
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: users-microservice-secrets
                  key: DB_NAME
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: users-microservice-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRATION
              value: "24h"
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: users-microservice-secrets
                  key: REFRESH_TOKEN_SECRET
            - name: REFRESH_TOKEN_EXPIRATION
              value: "7d"
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10 