# WARNING: Do not use this file in production. Create secrets manually or use an external secrets manager.
apiVersion: v1
kind: Secret
metadata:
  name: users-microservice-secrets
  labels:
    app: users-microservice
stringData:
  DB_USER: "postgres"
  DB_PASS: "postgres"
  DB_NAME: "users_microservice"
  JWT_SECRET: "changeThisSecretInProduction"
  REFRESH_TOKEN_SECRET: "anotherSecretToChange" 