apiVersion: v1
kind: Service
metadata:
  name: users-microservice
  namespace: users-microservice
  labels:
    app: users-microservice
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
      name: http
  selector:
    app: users-microservice 