apiVersion: v1
kind: Service
metadata:
  name: users-microservice
  labels:
    app: users-microservice
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: users-microservice 